### ISSUE TITLE
Rename to babbage.fiscal-data-package

### ISSUE THREAD

**Issue by pwalsh** [openspending/babbage.fiscal-data-package#1]
Yeah, I know it is clumsy. But, I like to do [queries like this](https://github.com/openspending?utf8=✓&query=fiscal-data-package) on GitHub orgs from the UI to fund related libs. I don't want to optimise for highly specific use cases but yeah.

**Comment by pudo** [comment]
Would the Python package then be ``babbage.fdp``? I'm totally easy on this.

**Comment by pwalsh** [comment]
Yes.

**Comment by pwalsh** [comment]
DONE
