### ISSUE TITLE
Export Babbage Model to Fiscal Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/babbage.fiscal-data-package#3]
# Description

As `babbage` will power the first API we expose for OpenSpending Next, it can be useful to have an interface to export Fiscal Data Packages out of Babbage (and, the database babbage works from).

Question: Do we really need to export?

# Tasks

* [ ] Write a loader from Babbage Model to Fiscal Data Package
* [ ] Decent unit test coverage, passing on Py 2.7, 3.3, 3.4, 3.5

**Comment by akariv** [comment]
#wontfix
